blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [

    path('', views.PostListView.as_view(), name='post_list'),
    path('post_list_delete/', views.PostListDeleteView.as_view(), name='post_list_delete'),
    path('post_list_edit/', views.PostUpdateListView.as_view(), name='post_list_edit'),
    path('post_list/<int:id>/delete/', views.PostDropDeleteView.as_view()),
    path('post_list/<int:id>/update/', views.PostEditView.as_view()),
    path('search/', views.SearchView.as_view(), name='search'),

    path('post_list/<int:id>/', views.PostDetailView.as_view()),
    path('create_post/', views.PostCreateView.as_view(), name='add_news'),
    path('hello/', views.hello_view),
    path('about_me/', views.about_view),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('product.urls')),
    path('', include('users.urls')),
    path('', include('parser.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

templates/filter_list.html
{% include 'header.html' %}
<br><br><br>
Фильтрация по продуктам
{% for i in product_eat %}
<h1>
    {{  i.name }}
</h1>
{% endfor%}
<hr>


Фильтрация по электроники
{% for i in product_electronic %}
<h1>
    {{  i.name }}
</h1>
{% endfor%}


{% include 'footer.html' %}

templates/footer.html

<footer class="bg-body-tertiary text-center text-lg-start">
  <!-- Grid container -->
  <div class="container p-4">
    <!--Grid row-->
    <div class="row">
      <!--Grid column-->
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <h5 class="text-uppercase">Главная</h5>

        <ul class="list-unstyled mb-0">
          <li>
            <a href="#!" class="text-body">Link 1</a>
          </li>
          <li>
            <a href="#!" class="text-body">Link 2</a>
          </li>
          <li>
            <a href="#!" class="text-body">Link 3</a>
          </li>
          <li>
            <a href="#!" class="text-body">Link 4</a>
          </li>
        </ul>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <h5 class="text-uppercase mb-0">Новости</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!" class="text-body">Link 1</a>
          </li>
          <li>
            <a href="#!" class="text-body">Link 2</a>
          </li>
          <li>
            <a href="#!" class="text-body">Link 3</a>
          </li>
          <li>
            <a href="#!" class="text-body">Link 4</a>
          </li>
        </ul>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <h5 class="text-uppercase">Адрес</h5>

        <ul class="list-unstyled mb-0">
          <li>
            <a href="#!" class="text-body">Link 1</a>
          </li>
          <li>
            <a href="#!" class="text-body">Link 2</a>
          </li>
          <li>
            <a href="#!" class="text-body">Link 3</a>
          </li>
          <li>
            <a href="#!" class="text-body">Link 4</a>
          </li>
        </ul>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <h5 class="text-uppercase mb-0">Контакты</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!" class="text-body">Link 1</a>
          </li>
          <li>
            <a href="#!" class="text-body">Link 2</a>
          </li>
          <li>
            <a href="#!" class="text-body">Link 3</a>
          </li>
          <li>
            <a href="#!" class="text-body">Link 4</a>
          </li>
        </ul>
      </div>
      <!--Grid column-->
    </div>
    <!--Grid row-->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2024 GEEKS-44-1B:
    <a class="text-body" href="https://mdbootstrap.com/"></a>
  </div>
  <!-- Copyright -->
</footer>
</body>
</html>

templates/header.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Geeks-Blog.kg</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>

<nav class="navbar  bg-dark navbar-expand-lg bg-body-tertiary fixed-top" data-bs-theme="dark" >
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Навбар</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Переключатель навигации">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'blog:post_list' %}">Главная</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'manas_film_list' %}">Фильмы Манаса</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            CRUD
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'blog:add_news' %}">Добавить</a></li>
            <li><a class="dropdown-item" href="{% url 'blog:post_list_delete' %}">Удалить</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'blog:post_list_edit' %}">Редактировать</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Отключенная</a>
        </li>
      </ul>
      <form action="{% url 'blog:search' %}" method="GET"  class="d-flex" role="search">
        <input class="form-control me-2" name="q" type="text" type="search" placeholder="Поиск" aria-label="Поиск">
        <button class="btn btn-outline-success" type="submit">Поиск</button>
      </form>
    </div>
  </div>
</nav>
<br><br>

templates/post_detail.html
{% load static %}
{% include 'header.html' %}
<link rel="stylesheet" href="{% static 'css/post_detail.css' %}">
<img src="{{ post_id.image.url }}" alt="" width="400" height="400">
<h1>{{ post_id.title }}</h1>
<p>{{ post_id.description }}</p>
<a href="{{ post_id.url_news }}">Перейти на сайт</a>
<p>{{ post_id.email_news }}</p>
<p> {{ post_id.like_or_dislike}}</p>


<div class="center">
    {% for j in post_id.review_post.all %}
    <p>
        <h3>{{ j.text_post }}</h3>
    </p>
    <p>{{ j.created_at }}</p>
    {% endfor %}
</div>


{% include 'footer.html' %}

templates/post_list.html
{% load static %}
{% include 'header.html' %}
<link rel="stylesheet" href="{% static 'css/post_list.css' %}">
<h1 class="text_color">Все новости</h1>


<div class="square_mom">
{% for i in post_object %}
<div class="card" style="width: 18rem;">
    <img src="{{ i.image.url }}" class="card-img-top" alt="...">
    <div class="card-body">
        <h5 class="card-title">{{ i.title }}</h5>
        <p class="card-text">{{ i.created_at }}</p>
        <a href="/post_list/{{ i.id }}/" class="btn btn-primary">Подробнее</a>
    </div>
</div>
{% endfor %}
</div>



{% include 'footer.html' %}